Web_Botnikov_90311/Models/ErrorViewModel.cs
using System;

namespace Web_Botnikov_90311.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web_Botnikov_90311/Models/MenuItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web_Botnikov_90311.Models
{
    public class MenuItem
    {
        // является ли страницей или методом контроллера
        public bool IsPage { get; set; } = false;
        // имя области
        public string Area { get; set; } = "";
        // имя действия контроллера
        public string Action { get; set; } = "";
        // имя контроллера
        public string Controller { get; set; } = "";
        // имя страницы
        public string Page { get; set; } = "";
        // класс CSS для текущего пункта меню
        public string Active { get; set; } = "";
        // текст надписи
        public string Text { get; set; } = "";
    }
}

Web_Botnikov_90311/Components/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web_Botnikov_90311.Components
{
    public class CartViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Web_Botnikov_90311/Components/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web_Botnikov_90311.Models;

namespace Web_Botnikov_90311.Components
{
    public class MenuViewComponent : ViewComponent
    {
        // Инициализация списка элементов меню
        private List<MenuItem> _menuItems = new List<MenuItem>
        {
            new MenuItem{ Controller="Home", Action="Index", Text="Lab 2"},
            new MenuItem{ Controller="Product", Action="Index",
            Text="Каталог"},
            new MenuItem{ IsPage=true, Area="Admin", Page="/Index",
            Text="Администрирование"},
            new MenuItem{ IsPage=true, Area="Admin", Page="/Index",
            Text="Ботников"}
        };

        public IViewComponentResult Invoke()
        {
            //Получение значений сегментов маршрута
            var controller = ViewContext.RouteData.Values["controller"];
            var page = ViewContext.RouteData.Values["page"];
            var area = ViewContext.RouteData.Values["area"];
            foreach (var item in _menuItems)
            {
                // Название контроллера совпадает?
                var _matchController = controller?.Equals(item.Controller)
                ?? false;
                // Название зоны совпадает?
                var _matchArea = area?.Equals(item.Area) ?? false;
                // Если есть совпадение, то сделать элемент меню активным
                // (применить соответствующий класс CSS)
                if (_matchController || _matchArea)
                {
                    item.Active = "active";
                }
            }
            return View(_menuItems);
        }
    }
}

Web_Botnikov_90311/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web_Botnikov_90311.Models;

namespace Web_Botnikov_90311.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Text"] = "Лабораторная работа 2";
            ViewData["Lst"] = new SelectList(_listDemo, "ListItemValue", "ListItemText");
            return View();
        }
        private List<ListDemo> _listDemo;
        public class ListDemo
        {
            public int ListItemValue { get; set; }
            public string ListItemText { get; set; }
        }

        public HomeController()
        {
            _listDemo = new List<ListDemo>
            {
                new ListDemo{ ListItemValue=1, ListItemText="Элемент 1"},
                new ListDemo{ ListItemValue=2, ListItemText="Элемент 2"},
                new ListDemo{ ListItemValue=3, ListItemText="Элемент 3"},
                new ListDemo{ ListItemValue=4, ListItemText="Элемент 4"}
            };
        }

    }
}

Web_Botnikov_90311/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная страница";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}


<main class="container">
    <h2>@ViewData["Text"]</h2>
    <h3>Список</h3> <br />
    <ol type="A">
        @for (int i = 1; i < 5; i++)
        {
            <li>элемент @i списка</li>
        }
    </ol>
    <hr />

    <h4>Форма</h4> <br />
    <form>
        <select asp-items="@ViewData["Lst"] as SelectList"></select>

        <div class="form-group row">
            <div class="col-sm-2"></div>
            <div class="col-sm-10">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="gridCheck1">
                    <label class="form-check-label" for="gridCheck1">
                        Чек-бокс 1
                    </label>

                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="gridCheck1">
                    <label class="form-check-label" for="gridCheck2">
                        Чек-бокс 2
                    </label>

                </div>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2"> Радио-кнопки </label>

            <div class="col-sm-10 offset-2">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                    <label class="form-check-label" for="inlineRadio1">Кнопка 1</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                    <label class="form-check-label" for="inlineRadio2">Кнопка 2</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">
                    <label class="form-check-label" for="inlineRadio3">Кнопка 3</label>
                </div>
            </div>

        </div>




        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 col-form-label">Логин</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" id="inputEmail3" placeholder="Введите логин">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 col-form-label">Пароль</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="inputPassword3" placeholder="Введите пароль">
            </div>

            <div class="form-group row">
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-primary">Войти</button>
                </div>
            </div>
        </div>
    </form>
</main>

Web_Botnikov_90311/Views/Shared/Components/Cart/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<a asp-controller="Cart" asp-action="Index"
   class="navbar-text ml-auto">
    00,0 руб.(0)
    <i class="fa fa-shopping-cart nav-color"></i>
</a>

Web_Botnikov_90311/Views/Shared/Components/Menu/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<MenuItem>
<div class="navbar-nav">
    @foreach (var item in Model)
    {
        @if (item.IsPage)
        {
            <a class="nav-item nav-link @item.Active"
               asp-area="@item.Area"
               asp-page="@item.Page">
                @item.Text
            </a>
        }
        else
        {
            <a class="nav-item nav-link @item.Active"
               asp-controller="@item.Controller"
               asp-action="@item.Action">
                @item.Text
            </a>
        }
    }
</div>

Web_Botnikov_90311/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_Botnikov_90311</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="lib/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header style="border:1px dotted red">
        <div class="container">
            <!-- Панель навигации -->
            <!--<span class="nav-color">Заголовок страницы</span>-->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- меню сайта -->
                @*<a class="navbar-brand" href="#">WebLabs_Botnikov_90311</a>
        <div class="navbar-nav">
            <a class="nav-item nav-link active" asp-controller="Home" aspaction="Index">Lab 2</a>
            <a class="nav-item nav-link" asp-controller="Product" aspaction="Index">Каталог</a>
            <a class="nav-item nav-link" asp-area="Admin" asppage="/Index">Администрирование</a>
        </div>*@
                <a class="navbar-brand" asp-action="Index" aspcontroller="Home">WebLabs_Botnikov_90311</a>
                <div class="navbar-nav">
                    @await Component.InvokeAsync("Menu")
                </div>
                <!-- меню сайта - конец -->
                <!-- Информация пользователя -->
                <a asp-controller="Cart" asp-action="Index" class="navbar-text mlauto">
                    00,0 руб <i class="fas fa-shopping-cart nav-color"></i> (0)
                </a>
                <div class="dropdown ml-4 nav-color">
                    <div class="dropdown-toggle" id="dropdownMenuButton"
                         data-toggle="dropdown"
                         aria-haspopup="true" aria-expanded="false">
                        <img src="~/images/avatar.jpg" width="30" alt="User"
                             class="rounded" />
                    </div>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <div class="dropdown-item-text">
                            <img src="~/images/avatar.jpg" width="50" alt="User"
                                 class="rounded" />
                            user@mail.ru
                        </div>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Cart" aspaction="Index">Мои товары</a>
                        <a class="dropdown-item" asp-area="Identity"
                           asp-page="/Account/Logout">Log off</a>
                    </div>
                </div>
                <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->
            <!--<span class="nav-color">Заголовок страницы</span>-->
        </div><!-- container - конец -->
    </header><!-- header - конец -->
    <main class="container" style="border:1px dotted green">
        @RenderBody();
    </main>
    <footer style="border:1px dotted red">
        >
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a><a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fab fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
            <!--<span class="nav-color">Подвал страницы</span>-->
        </div>
        <!--Содержимое страницы
        Панель навигации
        Подвал страницы-->
    </footer>
    <!-- Скрипты -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>

Web_Botnikov_90311/Views/Shared/_UserPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- Информация пользователя -->
@*<a href="#" class="navbar-text ml-auto">
    0,00 руб <i class="fas fa-shopping-cart nav-color"></i> (0)
</a>*@
@await Component.InvokeAsync("Cart")
<div class="dropdown ml-4 nav-color">
    <div class="dropdown-toggle" id="dropdownMenuButton"
         data-toggle="dropdown" aria-haspopup="true"
         aria-expanded="false">
        <img src="images/avatar.jpg" width="30"
             alt="User" class="rounded" />
    </div>
    <div class="dropdown-menu"
         aria-labelledby="dropdownMenuButton">
        <div class="dropdown-item-text">
            <img src="images/avatar.jpg" width="50"
                 alt="User" class="rounded" />
            user@mail.ru
        </div>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Мои товары</a>
        <a class="dropdown-item" href="#">Выход</a>
    </div>
</div>
<!-- Информация пользователя - конец -->